esphome:
  name: pn7160-spi-ci-test
  friendly_name: PN7160 SPI CI Test

esp32:
  board: esp32dev
  framework:
    type: arduino

logger:
  level: DEBUG

wifi:
  ssid: "CI_DUMMY_SSID"
  password: "CI_DUMMY_PASSWORD"

external_components:
  - source:
      type: local
      path: components
    components: [pn7160, pn7160_spi, pn7160_i2c]
    refresh: 0s

spi:
  clk_pin: GPIO18
  miso_pin: GPIO19
  mosi_pin: GPIO23

pn7160_spi:
  id: pn7160_board
  cs_pin: GPIO5
  irq_pin: GPIO17   # Required
  ven_pin: GPIO16   # Required
  health_check_enabled: true
  health_check_interval: 60s
  max_failed_checks: 3
  auto_reset_on_failure: true
  on_tag:
    then:
      - logger.log:
          format: "Tag scanned: %s"
          args: ['x.c_str()']
  on_tag_removed:
    then:
      - logger.log:
          format: "Tag removed: %s"
          args: ['x.c_str()']

binary_sensor:
  - platform: nfc
    name: "Test Badge SPI"
    uid: "04-A3-B2-C1-D4-E5-F6"
