esphome:
  name: pn7160-i2c-ci-test
  friendly_name: PN7160 I2C CI Test

esp32:
  board: esp32dev
  framework:
    type: arduino

logger:
  level: DEBUG

wifi:
  ssid: "CI_DUMMY_SSID"
  password: "CI_DUMMY_PASSWORD"

external_components:
  - source:
      type: local
      path: components
    components: [pn7160, pn7160_spi, pn7160_i2c]
    refresh: 0s

# CRITICAL: PN7160 requires I2C frequency >= 100kHz (bug #6339 fix)
i2c:
  sda: GPIO21
  scl: GPIO22
  scan: false
  frequency: 400kHz  # â† Must be >= 100kHz

pn7160_i2c:
  id: pn7160_board
  address: 0x28
  irq_pin: GPIO18   # Required
  ven_pin: GPIO19   # Required
  health_check_enabled: true
  health_check_interval: 60s
  max_failed_checks: 3
  auto_reset_on_failure: true
  on_tag:
    then:
      - logger.log:
          format: "Tag scanned: %s"
          args: ['x.c_str()']
  on_tag_removed:
    then:
      - logger.log:
          format: "Tag removed: %s"
          args: ['x.c_str()']

binary_sensor:
  - platform: nfc
    name: "Test Badge I2C"
    uid: "04-A3-B2-C1-D4-E5-F6"
