esphome:
  name: pn7160-wrover-test
  friendly_name: PN7160 Wrover Test

esp32:
  board: esp32dev
  framework:
    type: esp-idf

logger:
  level: VERY_VERBOSE
  
external_components:
  - source:
      type: local
      path: components
    components: [pn7160, pn7160_spi, pn7160_i2c]

i2c:
  sda: 32
  scl: 33
  frequency: 400kHz
  scan: false

pn7160_i2c:
  id: pn7160_board
  address: 0x28
  irq_pin: 26
  ven_pin: 27
  sensitivity: high
  on_tag:
    then:
      - logger.log:
          format: "Tag scanned: %s"
          args: ['x.c_str()']
  on_tag_removed:
    then:
      - logger.log:
          format: "Tag removed: %s"
          args: ['x.c_str()']

binary_sensor:
  - platform: nfc
    name: "Test Badge"
    uid: "04-A3-B2-C1-D4-E5-F6"
